### ISSUE TITLE
Initializing a new tenant : An error occurred while initializing the datastore: 42P07: relation "IX_Type" already exists

### ISSUE THREAD

**Issue by philippe-lavoie** [OrchardCMS/OrchardCore#1810]
I'm using master, I'll try the same in the dev branch.

Repro step:

I selected PostresSQL
Create a new Orchard Core site
Added a new tenant
Clicked on it
After I entered the results of the form, the following error was given

An error occurred while initializing the datastore: 42P07: relation "IX_Type" already exists

Expected:
no errors, creating a tenant should work :)

**Comment by philippe-lavoie** [comment]
When I specify a datastore for the new tenant, does it have to be a different one than the main site ?

**Comment by sebastienros** [comment]
Fixed in dev branch, please use dev

**Comment by philippe-lavoie** [comment]
It is not fixed if you don't create a new database. If I want my tenant to use the same database as I have and instead just rely on table prefixes to differentiate between the main site and the tenant's site.
