### ISSUE TITLE
Error submitting form because of disabled field

### ISSUE THREAD

**Issue by os1r1s110** [OrchardCMS/OrchardCore#1940]
The disabled field is not submitted along with the form, causing a validation error.

https://github.com/OrchardCMS/OrchardCore/blob/c15cc92233d6fc332df7291571aec28bf4c19b6f/src/OrchardCore.Modules/OrchardCore.Setup/Views/Setup/Index.cshtml#L151

**Comment by os1r1s110** [comment]
As I mentioned on the commit conversation, I'm not sure the `readonly` attribute works as expected on the select tag.

**Comment by sebastienros** [comment]
Works for me at least.

**Comment by os1r1s110** [comment]
Sorry, I thought it was not supported by reading the docs on [Mozzila website](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select)

It's all good then :)

**Comment by sebastienros** [comment]
Well I didn't try on Firefox :/ Can you try it?

**Comment by os1r1s110** [comment]
For me it doesn't even work on chrome with a simple repro as shown in this [fiddle](https://jsfiddle.net/65cLjpte/6/)

**Comment by os1r1s110** [comment]
Seems like [this stackOverflow post](https://stackoverflow.com/a/23428851) could be helpful here (if it's a real problem)

**Comment by sebastienros** [comment]
It's fixed in another branch actually by using a different technique, please try this one: https://github.com/OrchardCMS/OrchardCore/pull/1941

**Comment by os1r1s110** [comment]
Hmmm... there seems to be something weird there. On line [137](https://github.com/OrchardCMS/OrchardCore/blob/70729613256c5b22ae98c49db555d14db0180a3c/src/OrchardCore.Modules/OrchardCore.Setup/Views/Setup/Index.cshtml#L137), you have ` @if (!Model.DatabaseConfigurationPreset)` and then inside it you have `@if (Model.DatabaseConfigurationPreset)`, which will never resolve to true.

**Comment by os1r1s110** [comment]
You also still have the `readonly` attr set on line 150, which is still useless according to the docs linked above, but if you say it works in some circumstances and that it is sufficient, I won't complain ahah

**Comment by os1r1s110** [comment]
This should be reopened as there are still 2 errors remaining, the nested if condition which will never be true, and the readonly attribute which does not work as expected on select input element....

**Comment by jtkech** [comment]
- The story is that before when a provider was preselected we were not using a select input element but an individual hidden input. But the prefix and connection string were not correctly shown / hidden.

- Then, my bad, i re-used a select input which introduced the issue that the value was not posted.

- Now when a provider is preselected, the prefix and connection string are no more shown.

Then, as i have re-tried it, all seem to work fine unless a little thing (see below). That said.

- You are totally right, we now have the following pattern where `Part A` is useless.

      if (!Model.DatabaseConfigurationPreset)
      {
          ...
          if (Model.DatabaseConfigurationPreset)
          {
              // Part A
          }
          else
          {
              // Part B
          }

- I also saw a bad comment in `setup.js`.

- Finally, when **editing a tenant** the connection string is shown / hidden based on the selected provider, **but not the prefix** (it works when **creating a tenant**).

So, i will do a PR for this. Thanks for taking a look when it will be ready.

**Comment by sebastienros** [comment]
I don't understand the last issue you are describing. When I edit a tenant I can't see any database settings:

![image](https://user-images.githubusercontent.com/1165805/41897136-56c5fcee-78db-11e8-808a-924fa20ee50f.png)

So it's like we can't edit the connection information at all, and I am fine with that for now.
