### ISSUE TITLE
Odd behaviour happening in an async Widget Display Driver

### ISSUE THREAD

**Issue by marlon-tucker** [OrchardCMS/OrchardCore#1969]
Hi all,

Bit of a odd one here, difficult to explain but I'll do my best and if anything is unclear tell me.

I have a widget display driver, and in the Edit override I need to make a async call out to an external service, the returned object is not used on the widget settings object which is persisted in the database but it is used on the view model which is given to the partial razor page which renders the edit interface. When I do this, the widget fails to persist to the Orchard db, and does not render on the page.

If I take out the async call, it works. 

I then exchanged my external call for a `await Task.Delay(500)` as a sanity check, and the widget fails to save. 

Here is my code in the driver:

```
        public override Task<IDisplayResult> EditAsync(FormSettingsPart settingsPart, BuildPartEditorContext context)
        {
            return GenerateEditView(settingsPart);
        }

        private async Task<IDisplayResult> GenerateEditView(FormSettingsPart settingsPart)
        {
            await Task.Delay(500);
            //var formList = await _integrationSvc.GetActiveForms();

            return Initialize<FormSettingsPartEditViewModel>("FormSettingsPartEdit", vm =>
            {
                vm.LoadFromSettings(settingsPart);
                //vm.Forms = formList.ToList();
                vm.Forms = new List<string>();
            });
        }

        public override async Task<IDisplayResult> UpdateAsync(FormSettingsPart settingsPart, IUpdateModel updater)
        {
            await updater.TryUpdateModelAsync(settingsPart, Prefix);
            
            // populate the model with the unique Orchard widget id
            settingsPart.OrchardWidgetPrefix = Prefix;

            return await GenerateEditView(settingsPart);
        }
```

At the moment, I'm getting around this by making my service call synchronously which isn't particularly nice but will do for now.

Has anyone got any ideas as to what is happening here? It looks like something is not expecting something to be asynchronous, bet it all looks fine to me. No additional exceptions occur in the output between the working version and the non working one.

**Comment by sebastienros** [comment]
I tried by changing `TitlePartDisplay` to this:

```
using System.Threading.Tasks;
using OrchardCore.ContentManagement.Display.ContentDisplay;
using OrchardCore.ContentManagement.Display.Models;
using OrchardCore.DisplayManagement.ModelBinding;
using OrchardCore.DisplayManagement.Views;
using OrchardCore.Title.Model;
using OrchardCore.Title.ViewModels;

namespace OrchardCore.Title.Drivers
{
    public class TitlePartDisplay : ContentPartDisplayDriver<TitlePart>
    {
        public override IDisplayResult Display(TitlePart titlePart)
        {
            return Initialize<TitlePartViewModel>("TitlePart", model =>
            {
                model.Title = titlePart.Title;
                model.TitlePart = titlePart;
            })
            .Location("Detail", "Header:5")
            .Location("Summary", "Header:5");
        }

        public override Task<IDisplayResult> EditAsync(TitlePart titlePart, BuildPartEditorContext context)
        {
            return GenerateEditView(titlePart);
        }

        private async Task<IDisplayResult> GenerateEditView(TitlePart titlePart)
        {
            await Task.Delay(500);

            return Initialize<TitlePartViewModel>("TitlePart_Edit", model =>
            {
                model.Title = titlePart.Title;
                model.TitlePart = titlePart;

                return Task.CompletedTask;
            });
        }

        public override async Task<IDisplayResult> UpdateAsync(TitlePart model, IUpdateModel updater)
        {
            await updater.TryUpdateModelAsync(model, Prefix, t => t.Title);

            return await GenerateEditView(model);
        }
    }
}
```

But it works as expected.

**Comment by sebastienros** [comment]
Can you share some changes on any existing driver that I could use to repro the issue?

**Comment by marlon-tucker** [comment]
Is it important that the `Initialize` call returns a `Task` in the lambda? 

We are working with `1.0.0-beta2-5944` at the moment, so this may have been resolved at some point when you've gone to ASP Core 2.1 which I see has been recently merged. 

Unfortunately one of our projects hit this bug when upgrading to 2.1 https://github.com/aspnet/Security/issues/1765 so we have been holding off until it was absolutely necessary - which is now looking likely. 

If I wanted to try to debug the issue I am experiencing,  what area of Orchard handles saving content parts to the database - as in our case the whole part is effectively being set to null.

**Comment by sebastienros** [comment]
We did a fix for an issue that @paynecrl97 found and was related to async calls in shapes. I had missed an await, that could totally be the reason. Trying to find which one it is.

**Comment by sebastienros** [comment]
Found it: Please try this https://github.com/OrchardCMS/OrchardCore/issues/1082

**Comment by marlon-tucker** [comment]
hmm says that was merged in Oct 2017 though, meaning that has been fixed in the code base we are working from.

Or are you saying I should try making the `GenerateEditView` synchronous with a `async` lambda call in the `Initialize` function call?

Either way I'm off for the weekend so I'll try this on Monday, cheers for your time on this though.

**Comment by sebastienros** [comment]
No, I was just mentioning the bug we fixed.

I couldn't repro it so I will punt it to beta3 milestone. I would appreciate if you could provide some code that I can use to repro the issue locally, or if you could try this driver on the latest code base.

**Comment by marlon-tucker** [comment]
Just an update on this, we have updated our app to `1.0.0-beta3-67546` and it is still exhibiting the behaviour. 

I am seeing an exception happening in the pipeline located in the Autoroute Module, in file `AutoroutePartDisplay.cs` in this method:

```
        public override IDisplayResult Edit(AutoroutePart autoroutePart)
        {
            return Initialize<AutoroutePartViewModel>("AutoroutePart_Edit", async model =>
            {

                model.Path = autoroutePart.Path;
                model.AutoroutePart = autoroutePart;
                model.SetHomepage = false;

                var siteSettings = await _siteService.GetSiteSettingsAsync();
                var homeRoute = siteSettings.HomeRoute;
                if (homeRoute["area"]?.ToString() == "OrchardCore.Contents" &&
                    homeRoute["controller"]?.ToString() == "Item" &&
                    homeRoute["action"]?.ToString() == "Display" &&
                    autoroutePart.ContentItem.ContentItemId == homeRoute["contentItemId"]?.ToString())
                {
                    model.IsHomepage = true;
                }

                var contentTypeDefinition = _contentDefinitionManager.GetTypeDefinition(autoroutePart.ContentItem.ContentType);
                var contentTypePartDefinition = contentTypeDefinition.Parts.FirstOrDefault(x => String.Equals(x.PartDefinition.Name, nameof(AutoroutePart), StringComparison.Ordinal));
                model.Settings = contentTypePartDefinition.Settings.ToObject<AutoroutePartSettings>();
            });
        }
```

When the edit page is clicked, and the widget parts are loaded, the `homeRoute` variable is null and so this code throws a NullReferenceException, I am wondering if this is causing problems down the line? Does anyone know if that `HomeRoute` property should be automatically populated, or is our site recipe missing something?

However, this exception also occurs when I make my widget driver behave synchronously, so its probably a red haring but if I can prevent that NullReferenceException from happening at least I can narrow down my search.

**Comment by marlon-tucker** [comment]
Further update, I've now seen the `HomeRoute` should  be defined in the recipe, so I've fixed that in ours. However, the widget settings are still failing to persist to the database.

Is anyone able to tell me when these settings are stored in the database please?

Does it happen inside `await updater.TryUpdateModelAsync(settingsPart, Prefix);`?

**Comment by alberthajdu** [comment]
@sebastienros I can confirm that this issue is still exists. Did you try it with SQL server? Because this doesn't happen with SQLite.

I don't have exact repro steps but this is the behavior: if you set a property on the part and that set is **after an await**ed call then it won't persisted. But as soon as you change the await to .GetAwaiter().GetResult() then it will be persisted.

**Comment by marlon-tucker** [comment]
I confirm I am using SQL Server as a data store.

**Comment by Skrypt** [comment]
Maybe a Locking issue like we fixed in 01 recently.

**Comment by alberthajdu** [comment]
@sebastienros here's a repro.

1. latest dev, saas recipe, sql server.
2. enable html module, create a type with htmlbody.
3. create a new content item from that type, the htmlbody saves it's content, everything work well.
4. modify `HtmlBodyPartDisplay.UpdateAsync` by adding an innocent` await`ed query. It should look like this (it's position is crucial):
```
public override async Task<IDisplayResult> UpdateAsync(HtmlBodyPart model, IUpdateModel updater)
        {
            var viewModel = new HtmlBodyPartViewModel();

            await updater.TryUpdateModelAsync(viewModel, Prefix, t => t.Source);

            var test = await _session.Query<ContentItem, ContentItemIndex>(x => x.Owner == "admin").ListAsync();

            model.Html = viewModel.Source;

            return Edit(model);
        }
```
5. Modify htmlbody's content, save it, it's content won't be updated.

**Comment by jtkech** [comment]
Yes, i could repro. Here my first findings.

I first thought that after a `_session.Query()` you would need to do a `_session.Save()` but it is done in `OC.Contents.AdminController`.


    // The content item needs to be marked as saved (again) in case the drivers or the handlers have
    // executed some query which would flush the saved entities.
    // In this case the changes happening in handlers would not be taken into account.

    _session.Save(contentItem);


But anyway, i could repro, even with `SQLite` and by just using.

            var viewModel = new HtmlBodyPartViewModel();
            await updater.TryUpdateModelAsync(viewModel, Prefix, t => t.Source);
            await Task.Delay(500);
            model.Html = viewModel.Source;
            return Edit(model);

But if i change the order like this it works.

            var viewModel = new HtmlBodyPartViewModel();
            await updater.TryUpdateModelAsync(viewModel, Prefix, t => t.Source);
            model.Html = viewModel.Source;
            await Task.Delay(500);
            return Edit(model);

So, it seems that the model (here the `HtmlBodyPart`) needs to be fully updated before any other `await`. Hmm, i will try to understand what happens here.

**Comment by jtkech** [comment]
Maybe i found the issue.

In `ContentPartDisplayDriver<TPart>`, `updating is not awaited before applying to the content item.

    Task<IDisplayResult> IContentPartDisplayDriver.UpdateEditorAsync(ContentPart ...)
    {
        ...
        var result = UpdateAsync(part, context.Updater, updateEditorContext);
        part.ContentItem.Apply(typePartDefinition.Name, part);
        return result;
    }

Using the following then it works.

    async Task<IDisplayResult> IContentPartDisplayDriver.UpdateEditorAsync(ContentPart ...)
    {
        ...
        var result = await UpdateAsync(part, context.Updater, updateEditorContext);
        part.ContentItem.Apply(typePartDefinition.Name, part);
        return result;
    }

I will do a PR, need to check if the same thing need to be done in other places.

**Comment by petedavis** [comment]
Should we be adding some roslyn analysers to the project to help find these non awaited method issues and show as a compile warning? These issues keep reoccurring and the are genuine problems.

https://github.com/dotnet/roslyn-analyzers
https://github.com/JosefPihrt/Roslynator

**Comment by jtkech** [comment]
@petedavis thanks for the links
