### ISSUE TITLE
Localization not working with data annotations unless app restarts

### ISSUE THREAD

**Issue by robbinvandenberg** [OrchardCMS/OrchardCore#2073]
Using:
OrchardCore.Localization.Core Version="1.0.0-beta2-67581"

When a model instance is first created the localized annotations messages (display, validations etc.) get loaded and everything is correct. Once the language is changed and a new instance of a model is created translations don't update.

This issue was mentioned back in february and was on the roadmap for beta2, but isn't fixed yet:
Ref: #1443 

Is this going to be fixed in the near future?

**Comment by Skrypt** [comment]
When you say the language is changed what do you mean precisely? I'm currently working on a culture settings pull request so I'm not sure what you mean by switching language since we don't have this in the current Beta 2 source code.

**Comment by robbinvandenberg** [comment]
- When I start the application with default language 'en', the data annotations are shown as expected in English
- When I start the application with default language 'nl', the data annotations are shown as expected in Dutch

But

- When I start the application with default language 'en', the data annotations are shown as expected in English, but when I change the language (e.g. add &culture=nl in the url) everything gets translated as expected to Dutch, except the data annotations which are still shown in English.

I hope this was more precisely.

**Comment by Skrypt** [comment]
Can you test this back against my culture-settings branch? I'm pretty sure the issue is that you don't set any SupportedCultures through the ASP.NET Core Localization middleware and it falls back to CultureInfo.CurrentCulture and CultureInfo.CurrentUICulture which is your system culture. I will try to test it on my side.

**Comment by robbinvandenberg** [comment]
I do set the SupportedCultures setting, this is my Startup.cs :

`private void ConfigureLocalization(IServiceCollection services)
        {
            // Add PO localization
            services.AddPortableObjectLocalization(options => options.ResourcesPath = "Localization");
            // Configure localization
            services.Configure<RequestLocalizationOptions>(options =>
            {
                // Set the supported cultures
                var supportedCultures = new List<CultureInfo>
                {
                    new CultureInfo("en"),
                    new CultureInfo("nl")
                };

                // State what the default culture for the application is. This will be used if no specific culture
                // can be determined for a given request.
                options.DefaultRequestCulture = new RequestCulture("en");
                // State which cultures the application supports.
                // These are the cultures the app supports for formatting numbers, dates, etc.
                options.SupportedCultures = supportedCultures;
                // These are the cultures the app supports for UI strings, i.e. we have localized resources for.
                options.SupportedUICultures = supportedCultures;
            });`

I will test it against your culture-settings branch.

**Comment by Skrypt** [comment]
If you can share the code that is not working I could help on my side too. But the thing I've noticed is that the ASP.NET Core middleware Providers are falling back to CultureInfo.CurrentCulture and CultureInfo.CurrentUICulture when no DefaultRequestCulture is supplied. Also try to see which CultureProvider is triggered.

**Comment by Skrypt** [comment]
I just found something here : https://github.com/ForEvolve/ForEvolve.AspNetCore.Localization

**Comment by Skrypt** [comment]
Ok found what's missing : https://docs.microsoft.com/en-us/aspnet/core/fundamentals/localization?view=aspnetcore-2.1#implement-a-strategy-to-select-the-languageculture-for-each-request

**Comment by Skrypt** [comment]
Try this and let me know if it works afterward.
![image](https://user-images.githubusercontent.com/3228637/42455905-8931e266-8361-11e8-86ed-e70ef4d12a55.png)

**Comment by robbinvandenberg** [comment]
I already had that in my ConfigureServices method:

```C#
// Add Mvc and Mvc view localization
            services.AddMvc()
                .AddViewLocalization(LanguageViewLocationExpanderFormat.Suffix)
                .AddDataAnnotationsLocalization();
```

Appreciate your effort!

**Comment by robbinvandenberg** [comment]
The data annotations are kind of being localized, because if I start my app with DefaultRequestCulture 'nl' the translations of the nl.po file are shown as expected for the data annotations. The problem is the data annotations aren't updated when requesting the page in another language as the specified DefaultRequestCulture which the application started with

**Comment by Skrypt** [comment]
Which Provider are you using? QueryString or Cookie or AcceptLanguageHeader?

**Comment by Skrypt** [comment]
It's working for me on the culture-settings branch.

**Comment by Skrypt** [comment]
I'm looking at your ConfigureLocalization() method and I think it's missing something.

```C#
            services.AddPortableObjectLocalization(options => options.ResourcesPath = "Localization");

            // Override the default localization file locations with Orchard specific ones
            services.Replace(ServiceDescriptor.Singleton<ILocalizationFileLocationProvider, ModularPoFileLocationProvider>());
```

**Comment by robbinvandenberg** [comment]
I am using the default provider, which is a combination of all three you named (querystring, cookie, header) with querystring as highest priority.

It is maybe good to mention that I only use the NuGet package OrchardCore.Localization.Core in my ASP.NET Core 2.1 project, not the full CMS of Orchard. 

Which is why I also can't add ModularPoFileLocationProvider as you mentioned because it's not included in the NuGet package, only in the Localization OrchardCore Module which is different from the NuGet package I use.

**Comment by Skrypt** [comment]
Fixed  by https://github.com/OrchardCMS/OrchardCore/pull/1892

**Comment by Suven10** [comment]
@Skrypt 
Localization not working with data annotations unless app restarts issue is still exists
I'm using OrchardCore.Localization.Core - 1.0.0-beta2-67846
Still I can't able to validate data annotations with different locales.

**Comment by Skrypt** [comment]
https://github.com/OrchardCMS/OrchardCore/blob/dev/src/OrchardCore/OrchardCore.Mvc.Core/Startup.cs#L48
Here is where it is initialized. Also, from where is it failing to work?

**Comment by Suven10** [comment]
@Skrypt 
In startup.cs everything is configured as mentioned in the documentation. But when I start the application with default language 'en', the data annotations are shown as expected in English, but when I change the language (e.g. add &culture=nl in the url) everything gets translated as expected to Dutch, except the data annotations which are still shown in English.

I have added default culture as en and therefore when running the application all the them shown in English. then I appended the culture by using Querystring (ex - &culture=no in the url) to get translated from en to no. All of them including data annotation error display messages translated successfully to no. But when I change the culture again back to en everything got translated except data annotation error messages.

Important Note - I have both norwegian and english po files (no.po and en.po) in my project.

**Comment by Suven10** [comment]
@sebastienros 
How to get the beta3 prefixes in Nuget package?

**Comment by Suven10** [comment]
@Skrypt 
what do you mean by the tenant? In that case, how to fix this? Can I have some code samples?
Also I'm using asp.net core web application which will be started only one time with default culture as en. So my purpose is to change the locale of the application based on the culture.

**Comment by Skrypt** [comment]
![image](https://user-images.githubusercontent.com/3228637/45568461-b9320380-b82a-11e8-9261-0e78a59115b3.png)

Here you need to enable the tenant module and you will see your default tenant and have the option to reload it.

**Comment by Suven10** [comment]
@Skrypt 
I didn't get you. How to get this website up and running. I installed OrchardCore.Localization.Core - 1.0.0-beta2-67846 package via NuGet package and as I mentioned everything works fine except for data annotations. When you deploy the web application and then run the url to see the web application with default culture. Thereafter, when you change the culture from URL everythings works except data annotation error messages. Please clarify me by explaining in deep. Thanks.

**Comment by Skrypt** [comment]
Are you also using OrchardCore.Mvc.Core ?

**Comment by Suven10** [comment]
No I'm using OrchardCore.Localization.Core version - 1.0.0-beta2-67846

**Comment by Skrypt** [comment]
If you are using a custom project with Nuget packages. You should normally have this in your startup.cs file which will load Orchard Core. 

https://github.com/OrchardCMS/OrchardCore/blob/dev/src/Templates/OrchardCore.Cms.Templates/content/OrchardCore.Templates.Cms.Web/Startup.cs

Else if you don't then it is up to you to add the AddDataAnnotationsLocalization() middleware to your app.

**Comment by Suven10** [comment]
yes I have AddDataAnnotationsLocalization()  added in my startup.cs but it does not work for data annotation as expected. Expectation of this is to localize data annotation error messages based on the culture passed in the URL. But it's not working though.

**Comment by Skrypt** [comment]
This is a custom solution you are bulding so I'd need to see what you are doing exactly, a small detail could make this behave quite differently. Are you trying to add this in your decoupled frontend solution?

**Comment by Suven10** [comment]
@Skrypt 
Below is what my requirement
I have Swedish and Norwegian clients who use my asp.net core web application. My web application is hosted in centralized environment. Both my clients are using same application respectively. So my requirement is to have translated application for both clients. All of them are working perfectly except the data annotation error messages. This is where I'm blocked now.

**Comment by Skrypt** [comment]
I understand those requirements, though, like I said, the Data Annotations should work perfectly if you are using Orchard Core with Nuget packages like it's documented. I'll do a double check to make sure. Else the issue is in your custom project.

**Comment by Suven10** [comment]
@Skrypt 
So as per your comment, it should work perfectly for both clients. When you deploy and run in one locale, thereafter even though u change the locale u will not see the data annotation error messages. I'm blocked with this issue for more than a day. I have followed the below document to configure Orchard.Localization.Core 
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/portable-object-localization?view=aspnetcore-2.1
https://gist.github.com/sebastienros/7980aad2ab33dd3a1c011fcf5a3f350c

Apart from that,  I have used services.AddDataAnnotationsLocalization() as well in my startup.cs

**Comment by Suven10** [comment]
@Skrypt 
Alright, Thank you so much for the replies. If I can get any good news regarding what I asked in future. Please comment on this ticket. Thanks.

**Comment by abdoneem** [comment]
Localization not working on deploy and cant find po files when publish can any one help me

**Comment by hishamco** [comment]
@abdoneem please file a new issue if you have a problem in localization

**Comment by CumpsD** [comment]
I am encountering this too and am currently debugging it, Data Annotations are not properly being translated.

I've currently traced it to `PortableObjectStringLocalizer` not getting hit at all. (It does get hit for my own strings which i translate with IStringLocalizer)

When I debug, I end up at `Mvc\Mvc.DataAnnotations\src\DataAnnotationsMetadataProvider.cs`

```csharp
// DisplayName
            // DisplayAttribute has precedence over DisplayNameAttribute.
            if (displayAttribute?.GetName() != null)
            {
                if (localizer != null &&
                    !string.IsNullOrEmpty(displayAttribute.Name) &&
                    displayAttribute.ResourceType == null)
                {
                    displayMetadata.DisplayName = () => localizer[displayAttribute.Name];
                }
                else
                {
                    displayMetadata.DisplayName = () => displayAttribute.GetName();
                }
            }
```

It does go in `displayMetadata.DisplayName = () => localizer[displayAttribute.Name];`

But when I put a breakpoint in the func, it never executes.

**Comment by hishamco** [comment]
@CumpsD please refer to https://github.com/OrchardCMS/OrchardCore/pull/4675

**Comment by CumpsD** [comment]
Thanks!

**Comment by CumpsD** [comment]
@hishamco it turned out to be a very different reason....

I am using FluentValidation, and after a lot of debugging, and with inspiration for the PR you linked, I fixed it with:

```csharp
            ValidatorOptions.DisplayNameResolver = (type, memberInfo, expression) =>
            {
                var displayName = DisplayNameCache.DefaultDisplayNameResolver(memberInfo);

                if (displayName == null)
                    return null;

                using (var scope = serviceScopeFactory.CreateScope())
                {
                    var serviceProvider = scope.ServiceProvider;
                    var localizer = serviceProvider.GetService<IStringLocalizerFactory>().Create(typeof(Startup));
                    return localizer[displayName];
                }
            };
```

Took a big tour, but glad to end with such a simple solution :)

**Comment by hishamco** [comment]
@CumpsD I didn't know that you 're using FluentValidation, anyhow it's good to hear that m PR was useful to fix your issue ;)

FYI `DisplayName` attribute has a common issue with localization
