### ISSUE TITLE
[GraphQL] Potential issue in ContentPickerField

### ISSUE THREAD

**Issue by carlwoodhouse** [OrchardCMS/OrchardCore#3029]
Hi, not sure if this is an issue or not ...

but in a custom module for something im working on i basically copied the method of resolving contentitemids found in this file for the contentpickerfield

https://github.com/OrchardCMS/OrchardCore/blob/ebca1b8595f6e452fb3a57c1fff58564bf663981/src/OrchardCore.Modules/OrchardCore.ContentFields/GraphQL/Types/ContentPickerFieldQueryObjectType.cs

basically i wrote the following extension method that copypasta that method but makes it re-usable for me....

``` 
    public static async Task<IEnumerable<ContentItem>> ResolveContentItems(this object userContext, IEnumerable<string> contentItemIds)
        {
            if (contentItemIds == null || userContext == null)
            {
                return Enumerable.Empty<ContentItem>();
            }

            var contentItemIdsToQuery = contentItemIds.ToList();

            if (contentItemIdsToQuery.Count == 0)
            {
                return Enumerable.Empty<ContentItem>();
            }

            if (contentItemIdsToQuery.Count == 1)
            {
                var resolvedContentItem = await userContext.ResolveContentItem(contentItemIdsToQuery.First());
                return resolvedContentItem != null ? new[] { resolvedContentItem } : Enumerable.Empty<ContentItem>();
            }


            var context = userContext as GraphQLContext;

            if (context == null)
            {
                return Enumerable.Empty<ContentItem>();
            }

            var session = context.ServiceProvider.GetService<ISession>();
            var contentItems = await session.Query<ContentItem, ContentItemIndex>(y => y.ContentItemId.IsIn(contentItemIdsToQuery) && y.Published).ListAsync();
            return contentItems.OrderBy(c => contentItemIds.ToImmutableArray().IndexOf(c.ContentItemId));        
        }
```

which is called as follows ...

``` 
            Field<ContentItemInterface>()
                .Name("articleSection")
                .ResolveAsync(async x => await x.ResolveContentItem(x.Source.ArticleSectionContentItemId))
                .Description("Articles may belong to one or more 'sections' in a magazine or newspaper, such as Sports, Lifestyle, etc.");
```

Now in my dataset (admittedly pretty large) when using sqlserver as the data provider, i often get the following exception

"There is already an open DataReader associated with this Command which must be closed first."

I can't replicate this with SQLite. And i've managed to fix it by wrapping ```context.ServiceProvider.GetService<ISession>();``` in its own scope .. but not sure if that is wise.

Thoughts ? this could also effect the field we have already in orchardcore i guess as its exactly the same (and potentially taxonomies which do something similar)

/cc @Jetski5822 @jrestall

**Comment by sebastienros** [comment]
Do you have a more detailed stack trace? Could be a bug in yessql, or an issue with the IServiceProvider.

**Comment by carlwoodhouse** [comment]
I can get you one tomorrow for sure

**Comment by sebastienros** [comment]
Even better if we can repro it locally. Any simple code change we should try? These kind of things @jtkech loves to fix.

**Comment by carlwoodhouse** [comment]
just seeing if i can get a stack trace now, and then will see if i can find some steps to replicate on a simpler dataset - and not in a custom module.

**Comment by carlwoodhouse** [comment]
For sure i know wrapping the get of ISession into a new scope 'fixes' the issue

**Comment by carlwoodhouse** [comment]
Ok for sure i can replicate it with the contentitempicker field, i can give instructions how to replicate it,

* Create a site pointed at sqlserver (without mars ;))
* Create a contenttype (i called mine TestType) with a title and a contentpickerfield (my field was called linked)
* Create a bunch of them, linked to each other - i just did like 10, and picked random ones to link too
* Run the below query ..
```
{
  testType {
    displayText,
    linked {
      contentItems {
        displayText
      }
    }
  }
}
```
Now i will say, enabling MARS fixes this for sure ... for both this test data, and my custom module / large dataset ... so if thats fine, then great ... but maybe we need to document it.

HOWEVER ...
Once this issue was cleared up ... i now have another one in my custom module / data ...

```An item with the same key has already been added. Key: 103```

```
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at YesSql.Session.Get[T](IList`1 documents) in C:\projects\yessql-un1yf\src\YesSql.Core\Session.cs:line 378
   at YesSql.Services.DefaultQuery.Query`1.FirstOrDefaultImpl() in C:\projects\yessql-un1yf\src\YesSql.Core\Services\DefaultQuery.cs:line 899
   at PatientCore.Schema.GraphQL.GraphQLContextExtensions.ResolveContentItem(Object userContext, String contentItemId) in C:\development\vsts\PatientCore\src\PatientCore.Modules\PatientCore.Schema.GraphQL\Extensions\GraphQLContextExtensions.cs:line 58
```
This is VERY intermittent and as of yet im unable to reproduce in with the pickerfield, thrown by the same thing as the previous queries though

**Comment by sebastienros** [comment]
Looks like both issues have the same root cause. Replicating it will probably show that a session is reused where it should not ...
Thanks for the explanation

**Comment by carlwoodhouse** [comment]
Probably also explains why my 'fix' work as i assume using a new scope there is forcing a new session.

**Comment by sebastienros** [comment]
Can you check that it's fixed with the latest dev branch (or when the packages are available)?

**Comment by carlwoodhouse** [comment]
Yes, will check later tonight or in the morning and confirm

**Comment by carlwoodhouse** [comment]
@sebastienros i pulled the latest dev and still get a MARS error with sql server.

**Comment by carlwoodhouse** [comment]
seems more intermittent now but def still occurs

**Comment by sebastienros** [comment]
I can repro, and currently looking at graphql for a cause. 
Mitigation is to do

```
var contentItems = session.Query<ContentItem, ContentItemIndex>(y => y.ContentItemId.IsIn(ids) && y.Published).ListAsync().GetAwaiter().GetResult();
return Task.FromResult<IEnumerable<ContentItem>>(contentItems.OrderBy(c => Array.IndexOf(x.Source.ContentItemIds, c.ContentItemId)));
```

**Comment by carlwoodhouse** [comment]
i assume its better to do that then use a new scope which is my current
mitigation

**Comment by sebastienros** [comment]
Finally I fixed it globally, you won't have to change any code after I merge this new PR.

**Comment by carlwoodhouse** [comment]
Great! Will let you know how I get on once it’s merged

**Comment by carlwoodhouse** [comment]
Ok i tried it in dev and it works as expected, nice one. I have to wait for ( https://github.com/OrchardCMS/OrchardCore/pull/3121 ) to appear on nuget to test it with my massive dataset in a project consuming mygfet packages tho :P think it will be fine though.

**Comment by carlwoodhouse** [comment]
@sebastienros yup totally fixed :) thanks
