### ISSUE TITLE
Invalid column name 'UserId' after applying 1.0.0-rc2-15400

### ISSUE THREAD

**Issue by scleaver** [OrchardCMS/OrchardCore#7562]
After applying 1.0.0-rc2-15400 to an existing site and logging in with OpenId config the following error occurs and users can not login also seems to happen on if you then login with a local account too  - may be related to #7560 

```
 OrchardCore.Users.Services.UserStore|ERROR|IUserEventHandler thrown from OrchardCore.Users.Workflows.Handlers.UserEventHandler by SqlException Microsoft.Data.SqlClient.SqlException (0x80131904): Invalid column name 'UserId'.
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at Microsoft.Data.SqlClient.SqlDataReader.get_MetaData()
   at Microsoft.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at Microsoft.Data.SqlClient.SqlCommand.CompleteAsyncExecuteReader(Boolean isInternal, Boolean forDescribeParameterEncryption)
   at Microsoft.Data.SqlClient.SqlCommand.InternalEndExecuteReader(IAsyncResult asyncResult, Boolean isInternal, String endMethod)
   at Microsoft.Data.SqlClient.SqlCommand.EndExecuteReaderInternal(IAsyncResult asyncResult)
   at Microsoft.Data.SqlClient.SqlCommand.EndExecuteReaderAsync(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at Dapper.SqlMapper.ExecuteScalarImplAsync[T](IDbConnection cnn, CommandDefinition command)
   at YesSql.Commands.CreateIndexCommand.ExecuteAsync(DbConnection connection, DbTransaction transaction, ISqlDialect dialect, ILogger logger)
   at YesSql.Session.FlushAsync()
   at YesSql.Services.DefaultQuery.Query`1.ListImpl()
   at OrchardCore.Workflows.Services.WorkflowManager.TriggerEventAsync(String name, IDictionary`2 input, String correlationId, Boolean isExclusive, Boolean isAlwaysCorrelated) in C:\XXXXX/XXXXX\OrchardCore.Modules\OrchardCore.Workflows\Services\WorkflowManager.cs:line 116
   at OrchardCore.Modules.InvokeExtensions.InvokeAsync[TEvents,T1](IEnumerable`1 events, Func`3 dispatch, T1 arg1, ILogger logger) in C:\XXXXX/XXXXX\OrchardCore\OrchardCore.Abstractions\Modules\Extensions\InvokeExtensions.cs:line 133
ClientConnectionId:9d29b60c-8afb-4562-b4f1-882aa3778dad
Error Number:207,State:1,Class:16
ClientConnectionId before routing:cb72d1e3-a026-4654-967c-bd367b6d58f1
Routing Destination:XXXXXX.windows.net,11013    at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at Microsoft.Data.SqlClient.SqlDataReader.get_MetaData()
   at Microsoft.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at Microsoft.Data.SqlClient.SqlCommand.CompleteAsyncExecuteReader(Boolean isInternal, Boolean forDescribeParameterEncryption)
   at Microsoft.Data.SqlClient.SqlCommand.InternalEndExecuteReader(IAsyncResult asyncResult, Boolean isInternal, String endMethod)
   at Microsoft.Data.SqlClient.SqlCommand.EndExecuteReaderInternal(IAsyncResult asyncResult)
   at Microsoft.Data.SqlClient.SqlCommand.EndExecuteReaderAsync(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at Dapper.SqlMapper.ExecuteScalarImplAsync[T](IDbConnection cnn, CommandDefinition command)
   at YesSql.Commands.CreateIndexCommand.ExecuteAsync(DbConnection connection, DbTransaction transaction, ISqlDialect dialect, ILogger logger)
   at YesSql.Session.FlushAsync()
   at YesSql.Services.DefaultQuery.Query`1.ListImpl()
   at OrchardCore.Workflows.Services.WorkflowManager.TriggerEventAsync(String name, IDictionary`2 input, String correlationId, Boolean isExclusive, Boolean isAlwaysCorrelated) in C:\XXXXX/XXXXX\OrchardCore.Modules\OrchardCore.Workflows\Services\WorkflowManager.cs:line 116
   at OrchardCore.Modules.InvokeExtensions.InvokeAsync[TEvents,T1](IEnumerable`1 events, Func`3 dispatch, T1 arg1, ILogger logger) in C:\XXXXX/XXXXX\OrchardCore\OrchardCore.Abstractions\Modules\Extensions\InvokeExtensions.cs:line 133
```

**Comment by Skrypt** [comment]
Looks like the WorkflowManager causing the issue. Though if the database migration would have executed properly it should not have happened.

**Comment by sebastienros** [comment]
Or it's a workflow that creates a user?

**Comment by scleaver** [comment]
@sebastienros there is no workflow that create a user. This error throws as the existing user is returning from an external openid provider.

**Comment by sebastienros** [comment]
Would explain too, since we need to create a local user account in this case also. So definitely the issue I fixed. I am merging it since everyone else is sleeping.

**Comment by scleaver** [comment]
Thanks, @sebastienros really appreciate it

**Comment by scleaver** [comment]
@sebastienros unfortunately this didn't fix the issue will have to look further into it.

**Comment by deanmarcussen** [comment]
Did I break it?

@scleaver can you check that the `UserIndex` table now has a `UserId` column?

If it doesn't, or if the values are empty, the migration has failed.

Check the `Document` table for the `OrchardCore.Data.Migration.Records.DataMigrationRecord, OrchardCore.Data` and try reseting the `"OrchardCore.Users.Migrations","Version":6` to `"OrchardCore.Users.Migrations","Version":4` which should allow the migration to rerun.

Check logs during startup to see if it has run correctly.

The `UserId` column should be populated with the `UserName` (not the normalized name, the normal name)

**Comment by scleaver** [comment]
@deanmarcussen ok so yeah there is no userid column on that userindex and the user migrations is on 4. Can't see any migration errors in the log though

**Comment by Skrypt** [comment]
If you are using a Nuget package solution it should have worked unless maybe you extended the OrchardCore.Users module?

**Comment by deanmarcussen** [comment]
`YesSql.Commands.CreateIndexCommand.ExecuteAsync`

I can see from the log you gave it's trying to run, and then failing during a flush, possibly triggered by workflows.

I need a little more time to understand.

- can you login normally?
- start the site normally

**Comment by deanmarcussen** [comment]
Also try changing your log level to `Information`

It should log the migrations that are being run at startup.

We need to see that it is trying to run.
```
_logger.LogInformation("Applying migration for '{FeatureName}' from version {Version}.", featureId, current);`
```

My concern is that it hasn't properly flushed the migration commands, but last time I looked at YesSql table commands (i.e. create the UserId column) they were not queued, but executed directly against the table as commanded (some time ago I looked at that, so shakey on the exact behaviour)

**Comment by Skrypt** [comment]
We need to know what is doing the Workflow that gets triggered to understand better. It could be simply that the migration tries to execute on table records that is getting also updated by a Workflow at the same time. So this would be a session scope issue. But definitely here the code seems to have a UserId and the database doesn't so I'd suggest you disable the Workflow feature first and restart the website to see if the migration gets executed. That will fix your issue temporarly ; but I'm suspecting the issues lies somewhere else.

**Comment by scleaver** [comment]
Ok thanks guys for your help here. I will download the DB and try it locally so I can see what's happening.

I also notice the autoroute is not up to the correct version either.

**Comment by deanmarcussen** [comment]
> I also notice the autoroute is not up to the correct version either.

That's your problem. 

If `Autoroute` fails, then it will never get to the migration for users.
(I've seen this before)

Possible causes are an older version of sql (2014 and below from memory), which doesn't support one of the commands on the autoroute migrations.

Or slightly incorrect login credentials (dbo not assigned).

Let me know which one it is, as we have some more notes somewhere

**Comment by scleaver** [comment]
It is Azure SQL so it won't be 2014

I'll get back to you

**Comment by scleaver** [comment]
My connection string is just the normal Azure SQL specified one... anything not recommended in it below?

`Server=tcp:XXXX.database.windows.net,1433;Initial Catalog=XXX;Persist Security Info=False;User ID=XXXX;Password={your_password};MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;`

**Comment by deanmarcussen** [comment]
Check this issue https://github.com/sebastienros/yessql/issues/201

**Comment by scleaver** [comment]
> Check this issue https://github.com/sebastienros/yessql/issues/201

User has the default schema name dbo so it isn't that issue.

**Comment by scleaver** [comment]
Ok guys, looks like it might be an issue with custom migrations that is halting all migrations.

**Comment by deanmarcussen** [comment]
There is something about the nature of logging errors during migrations that is tricky.

Log level Information can help diagnosing because it might you a clearer picture of what is happening before they go into an error state

**Comment by scleaver** [comment]
Thanks @deanmarcussen, @sebastienros, and @Skrypt for helping me to sort this out. It was snot the OC code but something to do with a recipe we used in a custom migrations step. I am closing this now.
