### ISSUE TITLE
ConcurrencyException on Multi-Tenant

### ISSUE THREAD

**Issue by jeffolmstead** [OrchardCMS/OrchardCore#8470]
This might be most relevant to @jtkech - I upgraded to the latest code bits and now my multi-tenant (primary website) on my dev box throws this exception:

OrchardCore.Data.Documents.DocumentStoreCommitException: The 'SiteSettings' could not be persisted and cached as it has been changed by another process.
 ---> YesSql.ConcurrencyException: The document could not be updated as it has been changed by another process.
   at YesSql.Commands.UpdateDocumentCommand.ExecuteAsync(DbConnection connection, DbTransaction transaction, ISqlDialect dialect, ILogger logger)
   at YesSql.Session.FlushAsync()
   at YesSql.Session.CommitAsync()
   at YesSql.Session.CommitAsync()
   at OrchardCore.Data.Documents.DocumentStore.CommitAsync()
   --- End of inner exception stack trace ---
   at OrchardCore.Data.Documents.DocumentStore.<>c__11`1.<UpdateAsync>b__11_1(Exception exception)
   at OrchardCore.Data.Documents.DocumentStore.CommitAsync()
   at OrchardCore.Environment.Shell.Scope.ShellScope.BeforeDisposeAsync()
   at OrchardCore.Environment.Shell.Scope.ShellScope.UsingAsync(Func`2 execute, Boolean activateShell)
   at OrchardCore.Environment.Shell.Scope.ShellScope.ActivateShellInternalAsync()
   at OrchardCore.Environment.Shell.Scope.ShellScope.UsingAsync(Func`2 execute, Boolean activateShell)
   at OrchardCore.Modules.ModularTenantContainerMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

The lower level tenants work fine. It is a dev box so it isn't a huge deal, likely can blow away the main site and rebuild it without too much issue. However, if there is something important to try and figure out here, I will gladly help. I know Concurrency has been a topic in recent pull requests. I thought about removing each tenant (e.g. shell) to see if one of them could somehow be causing the issue. Look forward to any thoughts you have / how I might best diagnose this.

**Comment by jtkech** [comment]
We had the same kind of issue that has been fixed, the comments in #7449 may help us

I noticed that your trace has `YesSql.Session.CommitAsync()` twice

I would ask to check for a non awaited task in your code, but it was working before your upgrade

Which version you were using when it was working?

Need more thinkings, i will let you know

**Comment by jeffolmstead** [comment]
The prior working version was "1.0.0-rc2-15521". I will look for non await tasks in my code as well. From your history of seeing this this type of thing, do you think it is a downstream tenant causing the issues? Or would it be the top most site? I have very few features enabled in the top most site. I might pull off all the tenants and see what happens - will let you know.

**Comment by jeffolmstead** [comment]
I have removed all other tenants and problem still happening, so I have thrown a SQL profiler on it and here are the update methods encountered (in the order they happened):

**Update 1:**
exec sp_executesql N'update [TNT_Document] set [Content] = @Content_1, [Version] = @Version_1 where [Id] = @Id_1;
',N'@Version_1 bigint,@Content_1 nvarchar(715),@Id_1 int',@Version_1=5,@Content_1=N'{"Id":21,"DataMigrations":[{"DataMigrationClass":"OrchardCore.Recipes.Migrations","Version":1},{"DataMigrationClass":"OrchardCore.Users.Migrations","Version":8},{"DataMigrationClass":"OrchardCore.ContentManagement.Records.Migrations","Version":5},{"DataMigrationClass":"OrchardCore.Contents.Migrations","Version":1},{"DataMigrationClass":"OrchardCore.Liquid.Migrations","Version":1},{"DataMigrationClass":"OrchardCore.Media.Migrations","Version":1},{"DataMigrationClass":"OrchardCore.Commerce.Migrations.ProductMigrations","Version":1},{"DataMigrationClass":"OrchardCore.Commerce.Migrations.PriceMigrations","Version":1},{"DataMigrationClass":"OrchardCore.Commerce.Migrations.PriceVariantsMigrations","Version":1}]}',@Id_1=21

Note: Interesting that the commerce module migrations are running, I don't recall them being enabled, they would be the only "non-native" Orchard Core features. 

**Update 2:**
exec sp_executesql N'update [TNT_Document] set [Content] = @Content, [Version] = @Version where [Id] = @Id  and [Version] = 0 ;',N'@Content nvarchar(4000),@Id int,@Version bigint',@Content=N'{"MaxPagedCount":0,"MaxPageSize":100,"PageSize":10,"TimeZoneId":"America/New_York","ResourceDebugMode":0,"SiteName":"EMS Tenant Hosting","SiteSalt":"removedforsecurity","SuperUser":"manager","UseCdn":false,"HomeRoute":{"Action":"Index","Controller":"Home","Area":"TheTheme"},"AppendVersion":true,"CacheMode":0,"Properties":{"CurrentThemeName":"TheTheme","CurrentAdminThemeName":"TheAdmin","name":"settings","MediaTokenSettings":{"HashKey":"removedforsecurity"}},"Identifier":"4mrnajds374m1sftt6bxqt1c5p"}',@Id=42,@Version=1

Note: This one looks more relevant as it is updating Site Settings

**Update 3:**
exec sp_executesql N'update [TNT_Document] set [Content] = @Content_1, [Version] = @Version_1 where [Id] = @Id_1;
',N'@Version_1 bigint,@Content_1 nvarchar(715),@Id_1 int',@Version_1=5,@Content_1=N'{"Id":21,"DataMigrations":[{"DataMigrationClass":"OrchardCore.Recipes.Migrations","Version":1},{"DataMigrationClass":"OrchardCore.Users.Migrations","Version":8},{"DataMigrationClass":"OrchardCore.ContentManagement.Records.Migrations","Version":5},{"DataMigrationClass":"OrchardCore.Contents.Migrations","Version":1},{"DataMigrationClass":"OrchardCore.Liquid.Migrations","Version":1},{"DataMigrationClass":"OrchardCore.Media.Migrations","Version":1},{"DataMigrationClass":"OrchardCore.Commerce.Migrations.ProductMigrations","Version":1},{"DataMigrationClass":"OrchardCore.Commerce.Migrations.PriceMigrations","Version":1},{"DataMigrationClass":"OrchardCore.Commerce.Migrations.PriceVariantsMigrations","Version":1}]}',@Id_1=21

Note: That looks like a repeat of ***Update 1*** above...

**Update 4:**
exec sp_executesql N'update [TNT_Document] set [Content] = @Content, [Version] = @Version where [Id] = @Id  and [Version] = 0 ;',N'@Content nvarchar(4000),@Id int,@Version bigint',@Content=N'{"MaxPagedCount":0,"MaxPageSize":100,"PageSize":10,"TimeZoneId":"America/New_York","ResourceDebugMode":0,"SiteName":"EMS Tenant Hosting","SiteSalt":"removedforsecurity","SuperUser":"manager","UseCdn":false,"HomeRoute":{"Action":"Index","Controller":"Home","Area":"TheTheme"},"AppendVersion":true,"CacheMode":0,"Properties":{"CurrentThemeName":"TheTheme","CurrentAdminThemeName":"TheAdmin","name":"settings","MediaTokenSettings":{"HashKey":"removedforsecurity"}},"Identifier":"4yzpa8kdsmykr6jg6tdqasxnm4"}',@Id=42,@Version=1

Note: That looks like a repeat of ***Update 2*** above... Here is a picture (if it helps any):

![image](https://user-images.githubusercontent.com/1848585/106381713-c236b780-6388-11eb-8355-f92f49b8188f.png)

**Comment by jeffolmstead** [comment]
I checked to see what my current versions were for the DataMigration and I see it is going from OrchardCore.Users.Migrations version 6 to version 8, the rest are not changing. That would be the only migration being run, so I will look there now.

**Comment by jeffolmstead** [comment]
I have checked to see what was called in the update and nothing that impacted my site, so I just (via the database) changed the version from 6 to 8. I still get the remaining error (same as 2 and 4 above):

exec sp_executesql N'update [TNT_Document] set [Content] = @content, [Version] = @Version where [Id] = @id and [Version] = 0 ;',N'@content nvarchar(4000),@id int,@Version bigint',@content=N'{"MaxPagedCount":0,"MaxPageSize":100,"PageSize":10,"TimeZoneId":"America/New_York","ResourceDebugMode":0,"SiteName":"EMS Tenant Hosting","SiteSalt":"removedforsecurity","SuperUser":"manager","UseCdn":false,"HomeRoute":{"Action":"Index","Controller":"Home","Area":"TheTheme"},"AppendVersion":true,"CacheMode":0,"Properties":{"CurrentThemeName":"TheTheme","CurrentAdminThemeName":"TheAdmin","name":"settings","MediaTokenSettings":{"HashKey":"removedforsecurity"}},"Identifier":"4mrnajds374m1sftt6bxqt1c5p"}',@id=42,@Version=1

And it is running twice. So, it isn't an issue with any one migration, something seems to be causing things to run twice...

**Comment by jeffolmstead** [comment]
I have now looked to see what it is trying to change on the Site Settings, and these are the new values:

**Top Level**
"BaseUrl":null,
 "Calendar":null,
 "Culture":"",
 "SupportedCultures":[],
"Identifier":"4q5xj9nqjjsx446sg60yb2j153"

**Nested Level**
Properties:{
  "MediaTokenSettings":{
    "HashKey":"removedforsecurity"
  }
}

I don't know if that provides more insights... I might just manually apply those settings just to see if it get's me past this and to see if the server keeps calling everything twice.

**Comment by jtkech** [comment]
Thanks for the infos

Yes, we have a new `MediaTokenSettingsUpdater` that updates site settings when activating the shell if there are no `HashKey` yet

Can't right now but will take a look this night

**Comment by jeffolmstead** [comment]
That is no problem, you provided me good ideas on where to start looking. Note, I have just updated the Site Settings via the database and everything is now working fine. Do you mind if I keep this open for a bit to see if you have further thoughts? Technically I am up and running with a work around of going direct to the database as detailed above.

**Comment by jtkech** [comment]
But we still need to fix this use case

So keep it open until i will able to repro on my side, which db do you use?

I will try it this night

**Comment by jeffolmstead** [comment]
Agreed. Yes, I am using a Microsoft SQL Server. Thanks again.

**Comment by jtkech** [comment]
@jeffolmstead 

> Interesting that the commerce module migrations are running, I don't recall them being enabled, they would be the only "non-native" Orchard Core features.

It doesn't mean that this migration has run, it only show the update of the migration document that includes all migrations versions

> This one looks more relevant as it is updating Site Settings

Yes with the new MediaTokenSettings HashKey

> That looks like a repeat of Update 1 above...

Yes, it session saves the migrations document on each migration, but normally it updates it once when committing the session. Normally concurrent migrations can only happen with multiple instances, see #7941.

> That looks like a repeat of Update 2 above...

Idem ;)

For infos we can remove the consistency checking per document type

         // In the Settings module startup
        services.Configure<DocumentOptions>(typeof(SiteSettings).FullName, options =>
        {
            options.CheckConsistency = false;
        });

Sorry, need more thinkings, still don't understand why there are 2 consecutive session `CommitAsync()` async calls

**Comment by jtkech** [comment]
@jeffolmstead 

So because i can't repro, i started to simulate things, e.g by throwing an exception in a migration, doing this i started to have quite the same kind of trace, for now just saw that in this case the tenant is not marked as activated and before fully failing, in the next created scope it starts a 2nd shell activation + migrations again

In fact the concurrency exception you saw would be just because of the new update of MediaTokenSettings in a shell activated handler that updates the site settings that are part of the documents on which we do a concurrency checking.

So i think that the concurrency issue is not related to the actual issue that would be a bad migration instead.

Can't right now but i think it's quite easy to prevent the duplicate migrations and log more useful infos.

I will do a PR soon so that you will be able to test it with your app

**Comment by jtkech** [comment]
@jeffolmstead 

> And it is running twice. So, it isn't an issue with any one migration, something seems to be causing things to run twice...

Okay, but then why it fails to update the site settings

Just noticed that in your profiled query there is `where [Id] = @id and [Version] = 0`, this is where it does the concurrency checking, but normally the `Version` column is at least equal to 1. When i profile the same query i get e.g. `where [Id] = @id and [Version] = 8`. I also tried to remove the site settings document, in that case it creates one with  a version of 1.

But it seems that you have an existing site settings document, so, can you check the value of the `Version` column for your site settings document. Hmm, maybe it has a NULL value resulting in a failing `0 = NULL` comparison.

---

Otherwise, some other thoughts, but only if you have time

- Are you using the MARS option in your connection string? If so can you remove it and see what happens

- We had a similar issue #7449 that we fixed, so maybe a mix of assemblies, can you try a `git clean -xdf` if you are using the source code, or try to clean your solution, and then do a full re-build.

**Comment by jtkech** [comment]
@jeffolmstead 

See my above comment

Yes, setting the `Version` column of the setting document to `NULL` results in the exact same trace. So i think you just need to set it to a non null value.

    2021-02-02 07:05:57.0867|Default||eeed1852-4bfe6e1762572719.||Microsoft.AspNetCore.Server.IIS.Core.IISHttpServer|ERROR|Connection ID "17798225737568752594", Request ID "800013d3-0002-f700-b63f-84710c7967bb": An unhandled exception was thrown by the application.
    OrchardCore.Data.Documents.DocumentStoreCommitException: The 'SiteSettings' could not be persisted and cached as it has been changed by another process.
     ---> YesSql.ConcurrencyException: The document could not be updated as it has been changed by another process.
       at YesSql.Commands.UpdateDocumentCommand.ExecuteAsync(...)
       at YesSql.Session.FlushAsync()
       at YesSql.Session.CommitAsync()
       at YesSql.Session.CommitAsync()
       at OrchardCore.Data.Documents.DocumentStore.CommitAsync() in ...

We need to think about this use case, maybe on yesSql side

**Comment by jtkech** [comment]
I opened an issue on yesSql side https://github.com/sebastienros/yessql/issues/343

**Comment by jtkech** [comment]
Hi @jeffolmstead, are you still alive ;)

Can you confirm that the Version column of your site settings document is (or was) NULL?

**Comment by jeffolmstead** [comment]
@jtkech barely alive! Lot's of snow, lot's of work. I just checked though and yes, my Version is NULL:
![image](https://user-images.githubusercontent.com/1848585/106739280-f3142800-65e6-11eb-8a10-47ace7a6fda1.png)

It is "NULL" in a couple of my other old tenants also (though a newly created tenant has a numeric in it). So it looks like if the yesSql request you made can go through, it will be very beneficial.

**Comment by jtkech** [comment]
@jeffolmstead Thanks for confirming that the Version is null, it explains the issue

Normally, when creating / migrating the Document table, yesSql uses a default Version value of 0

But, as in your case, the Version column may have NULL values

So, i will follow https://github.com/sebastienros/yessql/issues/343
